### PR TITLE
Feature/build settings

### PR DESCRIPTION
**Pull request by FabioDubois**

### CODE REVIEW

**Comment by FabioDubois** [comment]
@kholtmann Can you have a look?

**Comment by FabioDubois** [comment]
@samuelba Thanks for adding the jenkins file. I had the same intention with https://github.com/leggedrobotics/dynamixel_motor/pull/1/commits/cc2662cdd8563f27b200dac6bfd6a4c16d4849fa
;D

Can you review/approve the additional changes in the README?

**Comment by samuelba** [comment]
Ups, didn't see the pull request. You could add the pre-release and release build status too.

**Comment by FabioDubois** [comment]
Good to merge?

**Comment by samuelba** [comment]
Something looks strange, otherwise yes:

selection_017

**Pull request merged**
